networks:
  net:
    driver: bridge

services:

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission-nas
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - USER=${USER_TRANSMISSION}
      - PASS=${PWD_TRANSMISSION}
    volumes:
      - "/docker/app-nas/transmission/data:/config"
      - "/ZFS/repo/transmission:/downloads"
      - "/ZFS/repo/transmission/torrents:/watch"
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - net
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-nas"

  resilio:
    container_name: resilio-nas
    image: lscr.io/linuxserver/resilio-sync:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - "/docker/app-nas/resilio/config:/config"
      - "/docker/app-nas/resilio/downloads:/downloads"
      - "/ZFS:/sync"
    ports:
      - 8888:8888
      - 55555:55555
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-nas"

  vaultwarden:
    container_name: vaultwarden-nas
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - "/docker/app-nas/vaultwarden:/data/"
    ports:
      - 4000:80
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-nas"

  firefox:
    image: jlesage/firefox:latest
    container_name: firefox-nas
    ports:
      - "5800:5800"
    restart: unless-stopped
    networks:
      - net
    volumes:
      - "/docker/app-nas/firefox:/config:rw"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-nas"
