version: "3.8"

networks:
  net:
    driver: bridge

services:

  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    container_name: filebrowser-nas
    ports:
      - 1000:8080
    networks:
      - net
    volumes:
      - "/ZFS:/data"
      - "/docker/filebrowser/config/:/config"
    environment:
      - "FB_BASEURL=/filebrowser"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-admin"

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission-nas
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - USER=${USER_TRANSMISSION}
      - PASS=${PWD_TRANSMISSION}
    volumes:
      - "/docker/transmission/data:/config"
      - "/ZFS/repo/torrents-transmission/downloads:/downloads"
      - "/ZFS/repo/torrents:/watch"
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-admin"

  vaultwarden-marcos:
    container_name: vaultwarden-marcos-nas
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - "/docker/vaultwarden-marcos:/data/"
    ports:
      - 4000:80
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-admin"

  vaultwarden-mel:
    container_name: vaultwarden-mel-nas
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - "/docker/vaultwarden-mel:/data/"
    ports:
      - 4010:80
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-admin"

  watchtower:
    container_name: watchtower-nas
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_SCHEDULE= 0 0 0 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAILURLFROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAILURLTO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTPSERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${EMAILPORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAILOGIN}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${APPPASSWORD}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    networks:
      - net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "org.label-schema.group=app-admin"

  resilio:
    container_name: resilio-nas
    image: lscr.io/linuxserver/resilio-sync:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - "/docker/resilio/config:/config"
      - "/docker/resilio/downloads:/downloads"
      - "/ZFS:/sync"
    ports:
      - 8888:8888
      - 55555:55555
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-admin"
