networks:
  net:
    driver: bridge

services:

  watchtower:
    container_name: watchtower-vps
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_SCHEDULE= 0 0 3 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAILURLFROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAILURLTO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTPSERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${EMAILPORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAILOGIN}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${APPPASSWORD}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    networks:
      - net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "org.label-schema.group=app-vps"
