version: "3.8"

networks:
  net:
    driver: bridge

services:

  vaultwarden:
    container_name: vaultwarden-vps
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - "/docker/vaultwarden/data:/data/"
    ports:
      - 4000:80
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-vps"

  watchtower:
    container_name: watchtower-vps
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_SCHEDULE= 0 0 3 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NO_PULL=true

#      - WATCHTOWER_NOTIFICATIONS=email
#      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAILURLFROM}
#      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAILURLTO}
#      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTPSERVER}
#      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${EMAILPORT}
#      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAILOGIN}
#      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${APPPASSWORD}
#      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2

      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${URL_SLACK}
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${SLACK_MAJ_CONTAINERS_IDENTIFIER}
#      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=${SLACK_CHANNEL_MAJ_CONTAINERS}
    networks:
      - net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "org.label-schema.group=app-vps"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-vps
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-vps"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-vps
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - net
    labels:
      - "org.label-schema.group=app-vps"
