networks:
  net:
    driver: bridge

services:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome-nas
    ports:
      - 4533:4533
    networks:
      - net
    restart: always
    environment:
      - ND_SCANSCHEDULE=24h
    volumes:
      - "/docker/app-media/navidrome/data:/data"
      - "/ZFS/musiques/navidrome:/music"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-media"

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfin-nas
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - JELLYFIN_PublishedServerUrl=https://tv.pariteau.fr
    volumes:
      - /docker/app-media/jellyfin/config:/config
      - /docker/app-media/jellyfin/cache:/cache
      - /ZFS/tv:/media
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
    networks:
      - net
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-media"
