version: "3.8"

networks:
  net:
    driver: bridge

services:

  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    container_name: filebrowser
    ports:
      - 1000:8080
    networks:
      - net
    volumes:
      - "/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/:/data"
      - "/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/filebrowser/config/:/config"
    environment:
      - "FB_BASEURL=/filebrowser"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    volumes:
      - "/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/nginx-proxy-manager:/data/"
      - "/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/nginx-proxy-manager:/letsencrypt/"
      - "/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/nginx-proxy-manager:/etc/letsencrypt/"
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - "/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/vaultwarden:/data/"
    ports:
      - 4000:80
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.no-pull=true"

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_SCHEDULE= 0 0 3 * * *
      - WATCHTOWER_CLEANUP=true
#      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NO_PULL=true
#      - WATCHTOWER_NOTIFICATIONS=gotify
#      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${token}
#      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=${url}
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${emailurlfrom}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${emailurlto}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${smtpserver}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${emailport}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${emaillogin}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${apppassword}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    networks:
      - net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
