services:

networks:
  net:
    driver: bridge
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-nas
    ports:
      - 3000:3000
    networks:
      - net
    restart: unless-stopped
    volumes:
      - /docker/app-monitoring/grafana/data:/var/lib/grafana
      - /docker/app-monitoring/grafana/config:/etc/grafana
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-nas
    ports:
      - 8098:8080
    networks:
      - net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-monitoring"

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus-nas
    ports:
      - 9090:9090
    networks:
      - net
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - /docker/app-monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - /docker/app-monitoring/prometheus/data:/prometheus
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-monitoring"
