version: '3'
services:
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser:latest
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      - FB_BASEURL=/filebrowser
    volumes:
      - '/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153:/data'
      - '/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/filebrowser/config:/config'
    ports:
      - 1000:1000
    labels:
      - com.centurylinklabs.watchtower.enable=true
