version: "3.8"
services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    container_name: filebrowser
    ports:
      - 1000:8080
    volumes:
      - "/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/:/data"
      - "/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/filebrowser/config/:/config"
    environment:
      - "FB_BASEURL=/filebrowser"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
