version: "2"
services:
  gotify:
    image: ghcr.io/gotify/server:latest
    container_name: gotify
    ports:
      - 2222:80
    environment:
      - GOTIFY_DATABASE_DIALECT=sqlite3
      - GOTIFY_DATABASE_CONNECTION=data/gotify.db
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=admin
      - GOTIFY_PASSSTRENGTH=10
      - GOTIFY_UPLOADEDIMAGESDIR=data/images
      - GOTIFY_PLUGINSDIR=data/plugins
      - TZ=Europe/Paris
    volumes:
      - ./config:/app/data
