version: '3.8'
services:
  gotify:
    container_name: gotify
    restart: unless-stopped
    image: gotify/server:latest
    ports:
      - 4080:80
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${username}
      - GOTIFY_DEFAULTUSER_PASS=${password}
      - TZ="Europe/Paris"
    volumes:
      - '/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/gotify/data:/app/data'
    networks:
      - frontend
      - backend
volumes:
  nfs_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${address},rw,soft,nfsvers=4
      device: ${path_nfs_data}
networks:
  backend:
    external: true
  frontend:
    external: true
