version: "3.8"

networks:
  net:
    driver: bridge
    config:
      -subnet: "172.40.0.0/16"

services:

  guacd-nas:
    image: guacamole/guacd:latest
    container_name: guacd-nas
    networks:
      - net:
        ipv4_address: 172.40.0.1
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-guacamole"

  mysql-guacamole-nas:
    image: mysql
    container_name: mysql-guacamole-nas
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /docker/guacamole/mysql:/var/lib/mysql
    networks:
      - net:
        ipv4_address: 172.40.0.2
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-guacamole"

  guacamole-nas:
    image: guacamole/guacamole:latest
    container_name: guacamole-nas
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    link:
      - guacd-nas
      - mysql
    ports:
      - 8080:8080
    networks:
      - net:
        ipv4_address: 172.40.0.3
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-guacamole"
