version: "3.8"

networks:
  net:
    driver: bridge

services:

  guacd-nas:
    image: guacamole/guacd:latest
    container_name: guacd-nas
    networks:
      - net
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-guacamole"

  mysql-guacamole-nas:
    image: mysql
    container_name: mysql-guacamole-nas
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=some_password
    volumes:
      - /docker/guacamole/mysql:/var/lib/mysql
    networks:
      - net
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-guacamole"

  guacamole-nas:
    image: guacamole/guacamole:latest
    container_name: guacamole-nas
    environment:
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=some_password
    link:
      - guacd-nas
      - mysql
    ports:
      - 8080:8080
    networks:
      - net
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-guacamole"
