version: "3.8"

networks:
  net:
    driver: bridge

services:

  guac-proxy:
    image: guacamole/guacd:latest
    container_name: guac-proxy
    expose:
      - 4822
    networks:
      - net
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-guac"

  guac-sql:
    image: mysql
    container_name: guac-sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /docker/guacamole/mysql:/var/lib/mysql
    expose:
      - 3306
    networks:
      - net
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "org.label-schema.group=app-guac"

  guac-web:
    image: guacamole/guacamole:latest
    container_name: guac-web
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - GUACD_HOSTNAME=guac-proxy
    depends_on:
      - guac-proxy
      - guac-sql
    links:
      - guac-proxy
    ports:
      - 8080:8080
    networks:
      - net
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-guac"
