networks:
  net:
    driver: bridge

services:

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: node_exporter-vps
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    ports:
      - '9100:9100'
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring-vps"
      - "com.centurylinklabs.watchtower.enable=true"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-vps
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: always
    ports:
      - '8080:8080'
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring-vps"
      - "com.centurylinklabs.watchtower.enable=true"
