version: '3'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /docker/monitoring/prometheus-data:/prometheus
      - /docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/monitoring/alertmanager/alert.rules/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    network_mode: "host"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - /docker/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /docker/monitoring/alertmanager/templates/default.tmpl:/etc/alertmanager/templates/default.tmpl
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    network_mode: "host"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - /docker/monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - /docker/monitoring/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - /docker/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /docker/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    network_mode: "host"

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    volumes:
    - /docker/monitoring/blackbox:/config
    network_mode: "host"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: "host"

volumes:
  prometheus-data:
  grafana-data:
