version: '3'

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - /docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/monitoring/alertmanager/alert.rules/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    network_mode: "host"

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    restart: unless-stopped
    volumes:
      - alertmanager-data:/alertmanager
      - /docker/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /docker/monitoring/alertmanager/templates/default.tmpl:/etc/alertmanager/templates/default.tmpl
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    network_mode: "host"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
#    environment:
#      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#      - /docker/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
    network_mode: "host"

  blackbox:
    container_name: blackbox_exporter
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    volumes:
    - /docker/monitoring/blackbox:/config
    network_mode: "host"

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    network_mode: "host"
