version: "3.8"

#volumes:
#  grafana_storage: {}

services:

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: '0'
    environment:
     - GF_SERVER_ROOT_URL=http://sup.pariteau.fr/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
#      - 'grafana_storage:/var/lib/grafana'
      - '/docker/monitoring/grafana:/var/lib/grafana'
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    volumes:
      - '/docker/monitoring/prometheus:/etc/prometheus'
      - '/docker/monitoring/prometheus:/prometheus'
      
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    ports:
      - '9100:9100'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
