version: '2.1'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/monitoring/prometheus/prometheus-data:/prometheus
    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana-test
    volumes:
      - /docker/monitoring/grafana/grafana_data:/var/lib/grafana
      - /docker/monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - /docker/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - '3000:3000'
