networks:
  net:
    driver: bridge

services:

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-nas
    restart: always
    volumes:
      - "/docker/app-proxy:/data/"
      - "/docker/app-proxy:/letsencrypt/"
      - "/docker/app-proxy:/etc/letsencrypt/"
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-system"
