networks:
  net:
    driver: bridge

services:
    
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-vps
    restart: always
    volumes:
      - "/docker/proxy:/data/"
      - "/docker/proxy:/letsencrypt/"
      - "/docker/proxy:/etc/letsencrypt/"
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=vps-system"
