version: "3.8"

networks:
  net:
    driver: bridge

volumes:
  prometheus-data: {}
  grafana-data: {}
#  alertmanager-data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - /docker/supervision/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/supervision/alertmanager/alert.rules/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=240h'
      - '--storage.tsdb.retention.size=5GB'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - net
    labels:
      - "org.label-schema.group=supervision"
      - "com.centurylinklabs.watchtower.enable=true"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
#      - alertmanager-data:/alertmanager
      - /docker/supervision/alertmanager/data:/alertmanager
      - /docker/supervision/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /docker/supervision/alertmanager/templates/default.tmpl:/etc/alertmanager/templates/default.tmpl
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    expose:
      - 9093
    networks:
      - net
    labels:
      - "org.label-schema.group=supervision"
      - "com.centurylinklabs.watchtower.enable=true"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - /docker/supervision/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - /docker/supervision/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - /docker/supervision/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /docker/supervision/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      - net
    labels:
      - "org.label-schema.group=supervision"
      - "com.centurylinklabs.watchtower.enable=true"

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    restart: unless-stopped
    volumes:
    - ./blackbox:/config
    expose:
      - 9115
    networks:
      - net
    labels:
      - "org.label-schema.group=supervision"
      - "com.centurylinklabs.watchtower.enable=true"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - net
    labels:
      - "org.label-schema.group=supervision"
      - "com.centurylinklabs.watchtower.enable=true"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    restart: unless-stopped
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - net
    labels:
      - "org.label-schema.group=supervision"
      - "com.centurylinklabs.watchtower.enable=true"

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - net
    labels:
      - "org.label-schema.group=supervision"
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 8080:8080
      - 9090:9090
      - 9093:9093
      - 9091:9091
      - 9115:9115
    volumes:
      - /docker/supervision/caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-$2a$14$1l.IozJx7xQRVmlkEQ32OeEEfP5mRxTpbDTCTcXRqn19gXD8YK1pO}
    restart: unless-stopped
    networks:
      - net
    labels:
      - "org.label-schema.group=supervision"
      - "com.centurylinklabs.watchtower.enable=true"
