version: "3.8"

networks:
  net:
    driver: bridge

volumes:
  prometheus-data: {}
  grafana-data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager/alert.rules/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d'
    expose:
      - 9090
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=true"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/templates/default.tmpl:/etc/alertmanager/templates/default.tmpl
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    expose:
      - 9093
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=true"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    expose:
      - 3000
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=true"

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    volumes:
    - ./blackbox:/config
    expose:
      - 3030
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=true"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    expose:
      - 9100
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=true"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=true"

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 3000:3000
      - 8080:8080
      - 9090:9090
      - 9093:9093
      - 9091:9091
      - 3030:3030
    volumes:
      - ./caddy:/etc/caddy
#    environment:
#      - ADMIN_USER=${ADMIN_USER:-admin}
#      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
#      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-$2a$14$1l.IozJx7xQRVmlkEQ32OeEEfP5mRxTpbDTCTcXRqn19gXD8YK1pO}
    restart: unless-stopped
    networks:
      - net
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=true"
