version: '3.3'
services:
  server:
    restart: unless-stopped
    container_name: vaultwarden
    volumes:
      - '/srv/dev-disk-by-uuid-4eabc91d-46b4-4d1d-9b18-5c13f7f80153/docker/vaultwarden:/data/'
    ports:
      - '4000:4000'
    image: vaultwarden/server:latest
