version: "2.3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:amd64-latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_SCHEDULE= 0 0 3 * * *
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
      - WATCHTOWER_NOTIFICATIONS=email \
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=naspariteau@gmail.com \
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=marcantoine.guimberteau@gmail.com \
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com \
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587 \
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=naspariteau@gmail.com \
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=musfgqatifhmhbuz \
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2 \
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
