version: '3.8'

networks:
  net:
    driver: bridge

volumes:
  wordpress-3:
  db-3:

services:

  wordpress:
    container_name: wordpress-vps-3
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 3000:80
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - wordpress-3:/var/www/html
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-vps"

  db:
    container_name: wordpress-db-vps-3
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-3:/var/lib/mysql
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=app-vps"
