networks:
  net:
    driver: bridge

services:

  wp-vps-dev:
    container_name: wp-vps-dev
    image: wordpress:latest
    restart: always
    ports:
      - 40000:80
    environment:
      - TZ=Europe/Paris
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - /docker/wp-dev/wp:/var/www/html
    networks:
      - net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.group=wordpress-vps"

  wp-db-vps-dev:
    container_name: wp-db-vps-dev
    image: mysql:8.0
    restart: always
    environment:
      - TZ=Europe/Paris
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --innodb-buffer-pool-size=256M --innodb-log-buffer-size=16M
    volumes:
      - /docker/wp/mysql:/var/lib/mysql
    networks:
      - net
    labels:
      - "org.label-schema.group=wordpress-vps"
